name: metro
description: Tabriz metro time table.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.1
  get: ^4.6.1
  flutter_spinkit: ^5.1.0
  dotted_line: ^3.1.0
  shared_preferences: ^2.0.13


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/images/

  fonts:
    - family: iranYekan
      fonts:
        - asset: assets/fonts/IRANYekanMobileBlack.ttf
          weight: 900
        - asset: assets/fonts/IRANYekanExtraBoldFaNum.ttf
          weight: 800
        - asset: assets/fonts/IRANYekanMobileBold.ttf
          weight: 700
        - asset: assets/fonts/IRANYekanMobileMedium.ttf
          weight: 500
        - asset: assets/fonts/IRANYekanMobileRegular.ttf
          weight: 400
        - asset: assets/fonts/IRANYekanMobileLight.ttf
          weight: 300
        - asset: assets/fonts/IRANYekanMobileThin.ttf
          weight: 100






